# Generated by Django 5.2.3 on 2025-06-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20210610_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de estudiante'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=30),
        ),
        migrations.CreateModel(
            name='costosMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscostos', to='administrativo.matricula')),
            ],
        ),
    ]
